const ID_FOR_EDIT_DEFAULT = 0;
const DEFAULT_COUNT = 10;
const LINK_PAGE_ACCOUNT_EDIT = '/accounts/edit';
const LINK_PAGE_ACCOUNT = '/accounts';
export { ID_FOR_EDIT_DEFAULT, DEFAULT_COUNT, LINK_PAGE_ACCOUNT_EDIT, LINK_PAGE_ACCOUNT };
