import { ID_FOR_EDIT_DEFAULT, DEFAULT_COUNT, LINK_PAGE_ACCOUNT_EDIT, LINK_PAGE_ACCOUNT } from './constantsDefault';

export { DEFAULT_COUNT, ID_FOR_EDIT_DEFAULT, LINK_PAGE_ACCOUNT_EDIT, LINK_PAGE_ACCOUNT };
